In [ ]:
def add_vectors(vector1, vector2):
  length = len(vector1)
  result = []
  for i in range(length):
    result.append(vector1[i] + vector2[i])
  return result

vector1 = [1, 2, 3]
vector2 = [5, 6, 7]

result = add_vectors(vector1, vector2)
print(result)

[6, 8, 10]


In [ ]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([5, 6, 7])

result = vector1 @ vector2
print(result)

38


In [ ]:
shape = (2, 3)
arr = np.zeros(shape)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
list_data = [[0]*5 for _ in range(4)]
print(list_data)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [ ]:
data = [4, 9, 2, 6]

result = [0 if x <= 4 else x for x in data]
print(result)

[0, 9, 0, 6]


In [ ]:
data = np.array([4, 9, 2, 6])
result = np.where(data <= 4, 0, data)
print(result)

[0 9 0 6]


In [ ]:
data1 = np.array([5, 3, 8, 7, 2])
data2 = np.array([2, 7, 3, 1, 8])

out = np.where(data1 > data2, data1, data2)
print(out)

[5 7 8 7 8]


In [ ]:
import numpy as np
import cv2

img = cv2.imread('stupid_boy.png', 3)
img = img.astype(float)

#increate brightness
img = img + 50
img = np.clip(img, 0, 255)

#save
img = img.astype(np.uint8)
cv2.imwrite('ans.png',img)

<class 'numpy.ndarray'>


True

In [ ]:
import numpy as np
import cv2

img = cv2.imread('stupid_boy.png', 3)
img = img.astype(float)

img[0:100, :] = 255
cv2.imwrite('output.png', img)

True

In [ ]:
u = np.array([3, 5, 7])

def get_value(u, a  )

In [ ]:
!pwd


/content


In [ ]:
!gdown 1sX9qmlPY1SXwboz9qOzjyLrkzCwYoT31

Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1sX9qmlPY1SXwboz9qOzjyLrkzCwYoT31 



In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
!cp /content/gdrive/MyDrive/cars_yolo_data.zip .

In [ ]:
!unzip cars_yolo_data.zip

Archive:  cars_yolo_data.zip
   creating: yolo_data/
   creating: yolo_data/val/
   creating: yolo_data/val/images/
  inflating: yolo_data/val/images/vid_4_28440.jpg  
  inflating: yolo_data/val/images/vid_4_13700.jpg  
  inflating: yolo_data/val/images/vid_4_1900.jpg  
  inflating: yolo_data/val/images/vid_4_9640.jpg  
  inflating: yolo_data/val/images/vid_4_13880.jpg  
  inflating: yolo_data/val/images/vid_4_1980.jpg  
  inflating: yolo_data/val/images/vid_4_9220.jpg  
  inflating: yolo_data/val/images/vid_4_26380.jpg  
  inflating: yolo_data/val/images/vid_4_12140.jpg  
  inflating: yolo_data/val/images/vid_4_26460.jpg  
  inflating: yolo_data/val/images/vid_4_9200.jpg  
  inflating: yolo_data/val/images/vid_4_21260.jpg  
  inflating: yolo_data/val/images/vid_4_2080.jpg  
  inflating: yolo_data/val/images/vid_4_3820.jpg  
  inflating: yolo_data/val/images/vid_4_6280.jpg  
  inflating: yolo_data/val/images/vid_4_9040.jpg  
  inflating: yolo_data/val/images/vid_4_30440.jpg  
  inflati

In [ ]:
!pip install ultraLytics
import ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 699.1/699.1 kB 9.5 MB/s eta 0:00:00


In [ ]:
ultralytics.checks()

Ultralytics YOLOv8.0.239 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.4/78.2 GB disk)


In [ ]:
import os
import cv2
import json

import matplotlib.pyplot as plt
from ultralytics import YOLO


In [ ]:
yolo_yaml_path = 'yolo_data/data.yml'
model = YOLO('yolov8s.yaml').load('yolov8s.pt')


                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256

100%|██████████| 21.5M/21.5M [00:00<00:00, 346MB/s]

Transferred 355/355 items from pretrained weights


In [ ]:
epochs = 15
imgsz = 640
batch_size = 8
patience = 5
lr = 0.0005

results = model.train(
    data = yolo_yaml_path,
    epochs = epochs,
    imgsz = imgsz,
    batch = batch_size,
    lr0 = lr,
    patience = patience,
    project = 'models',
    name = 'yolov8/detect/train'
)

Ultralytics YOLOv8.0.239 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8s.yaml, data=yolo_data/data.yml, epochs=15, time=None, patience=5, batch=8, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=models, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=

100%|██████████| 755k/755k [00:00<00:00, 48.0MB/s]


Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics

100%|██████████| 6.23M/6.23M [00:00<00:00, 320MB/s]


WARNING ⚠️ NMS time limit 0.550s exceeded
AMP: checks passed ✅


train: Scanning /content/yolo_data/train/labels... 345 images, 0 backgrounds, 0 corrupt: 100%|██████████| 345/345 [00:00<00:00, 1847.14it/s]


train: New cache created: /content/yolo_data/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/yolo_data/val/labels... 26 images, 0 backgrounds, 0 corrupt: 100%|██████████| 26/26 [00:00<00:00, 1164.09it/s]

val: New cache created: /content/yolo_data/val/labels.cache


Plotting labels to models/yolov8/detect/train/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.0005' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
15 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/15      2.31G      1.439      1.814      1.172          2        640: 100%|██████████| 44/44 [00:14<00:00,  2.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.22it/s]

                   all         26         28      0.405      0.929      0.436      0.287



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/15       2.4G      1.331     0.9723      1.153          1        640: 100%|██████████| 44/44 [00:10<00:00,  4.39it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.84it/s]

                   all         26         28      0.527      0.597      0.435      0.283



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/15      2.41G      1.302     0.8445      1.148          3        640: 100%|██████████| 44/44 [00:07<00:00,  5.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.80it/s]

                   all         26         28      0.459      0.857      0.476      0.293



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/15       2.4G      1.388      0.799      1.193          2        640: 100%|██████████| 44/44 [00:10<00:00,  4.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  6.58it/s]

                   all         26         28      0.429      0.857      0.494      0.297



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/15      2.41G      1.358     0.8114      1.209          2        640: 100%|██████████| 44/44 [00:09<00:00,  4.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.13it/s]

                   all         26         28      0.418      0.929      0.513      0.327


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/15      2.42G      1.309     0.8214      1.202          1        640: 100%|██████████| 44/44 [00:08<00:00,  5.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  6.64it/s]


                   all         26         28      0.469      0.786      0.483      0.322

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/15       2.4G      1.272     0.7588      1.144          1        640: 100%|██████████| 44/44 [00:09<00:00,  4.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  5.70it/s]

                   all         26         28      0.423      0.865      0.505      0.317



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/15      2.42G      1.282     0.7332      1.167          1        640: 100%|██████████| 44/44 [00:08<00:00,  4.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.54it/s]

                   all         26         28      0.433      0.964      0.504      0.299



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/15      2.39G      1.277     0.7159      1.156          1        640: 100%|██████████| 44/44 [00:07<00:00,  5.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  7.89it/s]

                   all         26         28       0.44      0.964      0.499      0.294



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/15      2.42G      1.215     0.6816      1.128          3        640: 100%|██████████| 44/44 [00:09<00:00,  4.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  6.48it/s]

                   all         26         28      0.414      0.964      0.538      0.357



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/15      2.39G      1.191     0.6523      1.119          1        640: 100%|██████████| 44/44 [00:07<00:00,  5.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  4.87it/s]

                   all         26         28      0.417      0.893      0.588      0.362



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/15       2.4G      1.171     0.6234      1.094          0        640: 100%|██████████| 44/44 [00:09<00:00,  4.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  9.20it/s]

                   all         26         28      0.424      0.964      0.549      0.373



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/15      2.41G      1.154     0.5965      1.105          1        640: 100%|██████████| 44/44 [00:09<00:00,  4.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.16it/s]

                   all         26         28      0.419      0.964      0.534      0.365



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/15       2.4G      1.123     0.5889      1.093          1        640: 100%|██████████| 44/44 [00:07<00:00,  5.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  8.77it/s]

                   all         26         28      0.429          1      0.578      0.407



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/15      2.42G      1.165     0.5748      1.083          2        640: 100%|██████████| 44/44 [00:10<00:00,  4.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  7.45it/s]

                   all         26         28      0.444          1      0.537       0.37



15 epochs completed in 0.046 hours.
Optimizer stripped from models/yolov8/detect/train/weights/last.pt, 22.5MB
Optimizer stripped from models/yolov8/detect/train/weights/best.pt, 22.5MB

Validating models/yolov8/detect/train/weights/best.pt...
Ultralytics YOLOv8.0.239 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
YOLOv8s summary (fused): 168 layers, 11125971 parameters, 0 gradients, 28.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  5.66it/s]


                   all         26         28      0.429          1      0.578      0.407
Speed: 0.1ms preprocess, 3.2ms inference, 0.0ms loss, 2.2ms postprocess per image
Results saved to models/yolov8/detect/train


In [ ]:
model_path = 'models/yolov8/detect/train/weights/best.pt'
test_img_path = '/content/yolo_data/val/images/vid_4_9620.jpg'

model = YOLO(model_path)
model.predict(test_img_path, save = True)


image 1/1 /content/yolo_data/val/images/vid_4_9620.jpg: 384x640 4 cars, 218.6ms
Speed: 11.8ms preprocess, 218.6ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs/detect/predict


[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'car'}
 obb: None
 orig_img: array([[[254, 253, 225],
         [254, 253, 225],
         [254, 253, 225],
         ...,
         [252, 250, 185],
         [252, 250, 185],
         [252, 250, 185]],
 
        [[254, 253, 225],
         [254, 253, 225],
         [254, 253, 225],
         ...,
         [252, 250, 185],
         [252, 250, 185],
         [252, 250, 185]],
 
        [[255, 254, 228],
         [255, 254, 228],
         [255, 254, 228],
         ...,
         [252, 250, 185],
         [253, 251, 186],
         [253, 251, 186]],
 
        ...,
 
        [[ 20,  42,  47],
         [ 72,  97, 101],
         [104, 133, 140],
         ...,
         [ 51,  52,  42],
         [ 40,  43,  34],
         [ 40,  44,  38]],
 
        [[ 61,  60,  50],
         [ 60,  61,  52],
         [ 46,  52,  47],
         ...,
         [101, 130, 1

In [2]:
from google.colab import files
files.download('Project Object Detection.ipynb')

FileNotFoundError: Cannot find file: Project Object Detection.ipynb

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
import sys
sys.path.append('drive')
import os
os.chdir('drive/MyDrive/Colab Notebooks')

In [8]:
!ls

'Project Object Dectection.ipynb'
